// ============================================================
// Mock Data — For frontend developer testing without API keys
// ============================================================

import type {
  RawEmail,
  AnalyzedEmail,
  ClassifiedEmail,
  EmailSummary,
  DraftReplies,
  ScheduledReminder,
  PipelineResult,
} from "@/types";

export const MOCK_RAW_EMAILS: RawEmail[] = [
  {
    id: "msg_urgent_01",
    threadId: "thread_budget_q3",
    from: "boss@company.com",
    fromName: "Budi Santoso (VP Product)",
    to: ["nibras@company.com"],
    cc: ["dimas@company.com", "sarah@company.com"],
    subject: "URGENT: Proposal Budget Q3 Marketing & Product Approval",
    bodyHtml: `<p>Hi Nibras,</p><p>Mohon review dan approve proposal budget Q3 yang sudah direvisi oleh tim marketing dan product. Total pengajuan <strong>Rp 500.000.000</strong> (alokasi digital ads naik 20%, event offline dipangkas).</p><p>Kita butuh approval final sebelum <strong>Jumat, 28 Juli 2026 jam 17.00 WIB</strong> agar pengajuan dana bisa diproses Finance minggu depan.</p><p>Detail dokumen terlampir.</p><p>Thanks,<br>Budi</p>`,
    bodyText: `Hi Nibras,\n\nMohon review dan approve proposal budget Q3 yang sudah direvisi oleh tim marketing dan product. Total pengajuan Rp 500.000.000 (alokasi digital ads naik 20%, event offline dipangkas).\n\nKita butuh approval final sebelum Jumat, 28 Juli 2026 jam 17.00 WIB agar pengajuan dana bisa diproses Finance minggu depan.\n\nDetail dokumen terlampir.\n\nThanks,\nBudi`,
    snippet: "Mohon review dan approve proposal budget Q3 yang sudah direvisi oleh tim marketing...",
    date: "2026-07-24T09:30:00.000Z",
    labels: ["INBOX", "UNREAD", "IMPORTANT"],
    attachments: [
      {
        filename: "Proposal_Budget_Q3_v2_Final.pdf",
        mimeType: "application/pdf",
        size: 2458000,
        attachmentId: "att_pdf_01",
      },
    ],
    isRead: false,
    isThread: true,
    threadLength: 3,
  },
  {
    id: "msg_high_02",
    threadId: "thread_client_tech",
    from: "andira@clientcorp.id",
    fromName: "Andira Putri (Client Lead)",
    to: ["nibras@company.com"],
    cc: [],
    subject: "Re: Update Project Milestone Phase 2 - Integration",
    bodyHtml: `<p>Halo Mas Nibras,</p><p>Mau konfirmasi untuk jadwal UAT (User Acceptance Testing) API Gmail Integration minggu depan. Apakah dari tim sudah siap untuk deployment ke staging environment pada hari Selasa?</p><p>Mohon ketersediaan waktunya juga untuk walkthrough demo pada Rabu pagi jam 10.00 WIB.</p><p>Salam,<br>Andira</p>`,
    bodyText: `Halo Mas Nibras,\n\nMau konfirmasi untuk jadwal UAT (User Acceptance Testing) API Gmail Integration minggu depan. Apakah dari tim sudah siap untuk deployment ke staging environment pada hari Selasa?\n\nMohon ketersediaan waktunya juga untuk walkthrough demo pada Rabu pagi jam 10.00 WIB.\n\nSalam,\nAndira`,
    snippet: "Mau konfirmasi untuk jadwal UAT (User Acceptance Testing) API Gmail Integration minggu depan...",
    date: "2026-07-24T08:15:00.000Z",
    labels: ["INBOX", "UNREAD"],
    attachments: [],
    isRead: false,
    isThread: false,
    threadLength: 1,
  },
  {
    id: "msg_medium_03",
    threadId: "thread_newsletter_ai",
    from: "newsletter@techdigest.io",
    fromName: "TechDigest Weekly",
    to: ["nibras@company.com"],
    cc: [],
    subject: "Weekly AI Pulse: Multi-Agent Systems in Production",
    bodyHtml: `<p>Welcome to this week's AI Digest! Top stories this week: How enterprise companies deploy multi-agent orchestration at scale using LLMs.</p>`,
    bodyText: `Welcome to this week's AI Digest! Top stories this week: How enterprise companies deploy multi-agent orchestration at scale using LLMs.`,
    snippet: "Welcome to this week's AI Digest! Top stories this week: How enterprise companies deploy...",
    date: "2026-07-24T06:00:00.000Z",
    labels: ["INBOX"],
    attachments: [],
    isRead: true,
    isThread: false,
    threadLength: 1,
  },
];

export const MOCK_PIPELINE_RESULTS: Record<string, PipelineResult> = {
  msg_urgent_01: {
    emailId: "msg_urgent_01",
    threadId: "thread_budget_q3",
    analysis: {
      emailId: "msg_urgent_01",
      threadId: "thread_budget_q3",
      from: "boss@company.com",
      fromName: "Budi Santoso (VP Product)",
      subject: "URGENT: Proposal Budget Q3 Marketing & Product Approval",
      intent: "approval",
      entities: {
        people: ["Dimas", "Sarah", "Budi"],
        dates: [{ text: "Jumat, 28 Juli 2026 jam 17.00 WIB", iso: "2026-07-28T17:00:00+07:00", isDeadline: true }],
        deadlines: [{ text: "Jumat, 28 Juli 2026 jam 17.00 WIB", iso: "2026-07-28T17:00:00+07:00", isDeadline: true }],
        amounts: [{ text: "Rp 500.000.000", value: 500000000, currency: "IDR" }],
        links: [],
        actionRequired: "Review dan berikan approval final proposal budget Q3",
        topics: ["Budget Q3", "Marketing", "Product Approval", "Finance"],
      },
      language: "id",
      needsReply: true,
      hasAttachment: true,
      sentiment: "urgent",
      wordCount: 68,
      isThread: true,
      threadLength: 3,
      rawEmail: MOCK_RAW_EMAILS[0],
    },
    classification: {
      emailId: "msg_urgent_01",
      threadId: "thread_budget_q3",
      from: "boss@company.com",
      fromName: "Budi Santoso (VP Product)",
      subject: "URGENT: Proposal Budget Q3 Marketing & Product Approval",
      intent: "approval",
      entities: {
        people: ["Dimas", "Sarah", "Budi"],
        dates: [{ text: "Jumat, 28 Juli 2026 jam 17.00 WIB", iso: "2026-07-28T17:00:00+07:00", isDeadline: true }],
        deadlines: [{ text: "Jumat, 28 Juli 2026 jam 17.00 WIB", iso: "2026-07-28T17:00:00+07:00", isDeadline: true }],
        amounts: [{ text: "Rp 500.000.000", value: 500000000, currency: "IDR" }],
        links: [],
        actionRequired: "Review dan berikan approval final proposal budget Q3",
        topics: ["Budget Q3", "Marketing", "Product Approval", "Finance"],
      },
      language: "id",
      needsReply: true,
      hasAttachment: true,
      sentiment: "urgent",
      wordCount: 68,
      isThread: true,
      threadLength: 3,
      rawEmail: MOCK_RAW_EMAILS[0],
      priority: 0,
      priorityLabel: "urgent",
      priorityScore: 95,
      priorityFactors: [
        { factor: "sender_importance", score: 95, reason: "Dikirim oleh VP Product (Atasan Direct)" },
        { factor: "deadline_proximity", score: 90, reason: "Deadline approval 28 Juli 2026" },
        { factor: "intent_urgency", score: 100, reason: "Perlu persetujuan dana sebelum diproses Finance" },
      ],
      routing: {
        shouldSummarize: true,
        shouldDraftReply: true,
        shouldSetReminder: true,
        reasons: ["Thread email panjang", "Butuh respons & approval", "Ada deadline eksplisit"],
      },
    },
    summary: {
      emailId: "msg_urgent_01",
      threadId: "thread_budget_q3",
      summary: {
        oneLiner: "Budi (VP Product) meminta approval budget Q3 sebesar Rp 500jt paling lambat Jumat 28 Juli.",
        detailed: [
          "Proposal budget Q3 tim Marketing & Product telah direvisi.",
          "Total pengajuan dana sebesar Rp 500.000.000 (alokasi Ads naik 20%, Event offline dikurangi).",
          "Dibutuhkan approval final dari Nibras sebelum Jumat 28 Juli 2026 pkl 17.00 WIB.",
          "Finance akan langsung memproses pencairan dana minggu depan setelah approval.",
        ],
      },
      actionItems: [
        {
          action: "Review dokumen Proposal_Budget_Q3_v2_Final.pdf",
          assignedTo: "user",
          deadline: "2026-07-28T17:00:00+07:00",
          isCompleted: false,
          priority: "urgent",
        },
        {
          action: "Kirim konfirmasi approval ke Budi & CC Finance",
          assignedTo: "user",
          deadline: "2026-07-28T17:00:00+07:00",
          isCompleted: false,
          priority: "urgent",
        },
      ],
      keyDecisions: [
        "Digital Ads budget dinaikkan 20%",
        "Budget event offline dipangkas",
      ],
      keyDates: [
        { text: "Jumat, 28 Juli 2026 17:00 WIB", iso: "2026-07-28T17:00:00+07:00", isDeadline: true },
      ],
    },
    draftReplies: {
      emailId: "msg_urgent_01",
      threadId: "thread_budget_q3",
      inReplyTo: "URGENT: Proposal Budget Q3 Marketing & Product Approval",
      drafts: [
        {
          id: "draft_01_formal",
          tone: "formal",
          subject: "Re: URGENT: Proposal Budget Q3 Marketing & Product Approval",
          body: "Halo Pak Budi,\n\nTerima kasih atas rincian proposalnya. Dokumen lampiran sudah saya terima dan akan segera saya review bersama tim hari ini. Approval resmi akan saya berikan sebelum deadline Jumat 28 Juli pkl 17.00 WIB.\n\nSalam,\nNibras",
          confidence: 0.95,
          includesContext: true,
        },
        {
          id: "draft_02_casual",
          tone: "casual",
          subject: "Re: URGENT: Proposal Budget Q3 Marketing & Product Approval",
          body: "Siap Pak Budi! Proposal budget Q3 udah aku terima. Nanti sore aku kaji ulang detailnya ya. Sebelum Jumat jam 5 sore pasti udah aku kirimkan approval-nya.\n\nThanks,\nNibras",
          confidence: 0.88,
          includesContext: true,
        },
        {
          id: "draft_03_assertive",
          tone: "assertive",
          subject: "Re: URGENT: Proposal Budget Q3 Marketing & Product Approval",
          body: "Noted Pak Budi. Saya setuju dengan penyesuaian alokasi digital ads ini. Saya akan cek dokumen PDF terlampir dan menyelesaikan approval sebelum Jumat sore.\n\nRegards,\nNibras",
          confidence: 0.90,
          includesContext: true,
        },
      ],
      quickActions: [
        { label: "Approved, Lanjutkan", body: "Halo Pak Budi, proposal budget Q3 sebesar Rp 500jt disetujui. Silakan diproses ke Finance. Terima kasih!", tone: "formal" },
        { label: "Akan Saya Review", body: "Siap Pak Budi, dokumen sudah diterima dan sedang saya review. Sebelum Jumat sore akan dikabari.", tone: "casual" },
        { label: "Minta Detail Ads", body: "Halo Pak Budi, mohon dikirimkan breakdown detail kenaikan 20% digital ads sebelum saya sign-off. Thanks!", tone: "formal" },
      ],
    },
    reminders: [
      {
        id: "rem_01",
        emailId: "msg_urgent_01",
        threadId: "thread_budget_q3",
        type: "deadline",
        remindAt: "2026-07-27T09:00:00.000Z",
        message: "⚡ Pengingat: H-1 Deadline Approval Budget Q3 (Rp 500jt) dari Pak Budi!",
        emailSubject: "URGENT: Proposal Budget Q3 Marketing & Product Approval",
        emailFrom: "Budi Santoso (VP Product)",
        escalationLevel: 1,
        isActive: true,
        relatedDeadline: "2026-07-28T17:00:00+07:00",
      },
    ],
    processedAt: "2026-07-24T09:30:05.000Z",
    processingTimeMs: 1420,
    errors: [],
  },
};
